### ISSUE TITLE
"configCAL_FACTOR" macro not defined in "error_hooks.cpp"

### ISSUE THREAD

**Issue by PKHarsimran** [Seeed-Studio/Seeed-Arduino-FreeRTOS#10]
**Describe the bug**
I encountered a compilation error when using the vNopDelayMS() function from the Seeed_Arduino_FreeRTOS library. The error message indicated that the configCAL_FACTOR macro was not defined in the scope where it was being used. After some investigation, I found that the configCAL_FACTOR macro was missing from the FreeRTOS configuration file, causing the compilation error.

To fix the issue, I added the following line to the **FreeRTOSConfig.h** file:
`#define configCAL_FACTOR ( configTICK_RATE_HZ / 1000 )`

**To Reproduce**

1.     Install the Seeed_Arduino_FreeRTOS library in the Arduino IDE.
2.     Create a new sketch and include the library header file.
3.     Call the vNopDelayMS() function with a delay value in milliseconds.
4.     Attempt to compile the sketch.

**Expected behavior**
The sketch should compile without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/22066581/235726209-e0231dcc-aa70-4efa-8924-0d79ef7bb6df.png)

**Comment by matsujirushi** [comment]
Note.

Definition of `configCAL_FACTOR` per CPU.

* SAMD51 ... [**NOT** declared](https://github.com/Seeed-Studio/Seeed_Arduino_FreeRTOS/blob/c14b7ec99f8942ee9141c250d6195ae79d299b16/src/arch/samd51/FreeRTOSConfig.h)
* SAMD21 ... [declared](https://github.com/Seeed-Studio/Seeed_Arduino_FreeRTOS/blob/c14b7ec99f8942ee9141c250d6195ae79d299b16/src/arch/samd21/FreeRTOSConfig.h#L71)
* STM32H7xx ... [**NOT** declared](https://github.com/Seeed-Studio/Seeed_Arduino_FreeRTOS/blob/c14b7ec99f8942ee9141c250d6195ae79d299b16/src/arch/stm32h7xx/FreeRTOSConfig.h)

**Comment by PKHarsimran** [comment]
True, I was trying to compile for SAMD51, Threw me the same exception. Can you please check. I was only able to fix it by putting 
 #define configCAL_FACTOR ( configTICK_RATE_HZ / 1000 )
  in SAMD51 config.h
Thankz
