### ISSUE TITLE
Multiple definition of delay

### ISSUE THREAD

**Issue by simon88** [Seeed-Studio/Seeed-Arduino-FreeRTOS#7]
Hi,
I got an error when I try to compiled for an `SAMD21E17A` `multiple definition of delay` conflit with `delay.c` in samd core and delay in `FreeRTOSVariant.c`

````
/*
 * override Arduino delay()
 */
extern void _real_delay(unsigned long ms);
void delay(unsigned long ms)
{
  if (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED)
  {
    vTaskDelay(ms / portTICK_PERIOD_MS);
  }
  else
  {
    _real_delay(ms);
  }
}
````

If I renamed this function by `delay2` for examle it's works but it's doesn't compile beceause `delay2` was not declared in this scope...

**Comment by LynnL4** [comment]
hi，`delay` is weak by default and should be able to be overloaded normally.
https://github.com/Seeed-Studio/ArduinoCore-samd/blob/d7c6a8f4b9661a3e28a25e11afca2c2c35f519f4/cores/arduino/delay.c#L138

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
